### ISSUE TITLE
Action triggers a warning: Unexpected input(s)

### ISSUE THREAD

**Issue by ghost** [bluwy/substitute-string-action#1]
When running the action (which performs as expected), the logs show a warning:

```
##[warning]Unexpected input(s) 'my_key', valid inputs are ['_input-text', '_input-file', '_output-file', '_format-key']
```

Is there a way that this warning could be silenced, either on the action side, or on the workflow side?

**Comment by bluwy** [comment]
Didn't notice this feature was added in Github Actions. There's a [community post](https://github.community/t/unwanted-warning-for-dynamic-input-properties-to-actions/116454) about it and it seems that it cannot be disabled. 

If you really need to suppress the warnings you could use the workaround showed in the link above for now. But since the issue happened since June, I'm not sure if GitHub will be fixing this any sooner.

Perhaps I could add this info in the README. Thanks for informing about this.

**Comment by ghost** [comment]
Hey there!

Thanks, it seems the workaround indeed suppresses the warning. Feel free to close this and I think it would be nice to include the workaround in the README indeed.

Cheers and thanks for a useful github action!

**Comment by bluwy** [comment]
No problem! I'll leave this open for now since the workaround isn't much a good solution. Will wait for updates on upstream to see if there's any real fix to have this action work as before.

**Comment by PipoLucido** [comment]
so.. Any solution?

**Comment by bluwy** [comment]
Closing this for now as there's not much to do here. The README currently have docs on this.
